# Problema 1: 
## Extraiga del internet la base de datos “wine-clustering.csv”  de la siguiente liga y agréguela a un DataFrame en Python.         https://www.kaggle.com/datasets/harrywang/wine-dataset-for-clustering

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors

Wine_C = pd.read_csv("wine-clustering.csv")
Wine_C.head()

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

## Mediante el algoritmo de K vecinos más cercanos determine el valor promedio de alcohol que tendrían los 5 vinos más parecidos a aquel con las características siguientes:

In [2]:
Prueba = Wine_C.iloc[:1,:].copy()

In [3]:
Prueba.loc[0,"Alcohol"] = 14
Prueba.loc[0,"Malic_Acid"] = 2
Prueba.loc[0,"Ash"] = 2.5
Prueba.loc[0,"Ash_Alcanity"] = 16
Prueba.loc[0,"Magnesium"] = 115
Prueba.loc[0,"Total_Phenols"] = 3
Prueba.loc[0,"Flavanoids"] = 2.5
Prueba.loc[0,"Nonflavanoid_Phenols"] = 0.4
Prueba.loc[0,"Proanthocyanins"] = 2
Prueba.loc[0,"Color_Intensity"] = 9
Prueba.loc[0,"Hue"] = 1
Prueba.loc[0,"OD280"] = 3.5
Prueba.loc[0,"Proline"] = 800
Prueba

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline
0,14.0,2.0,2.5,16.0,115,3.0,2.5,0.4,2.0,9.0,1.0,3.5,800

In [4]:
# Ejecucion del algoritmo KNN
k = 5
KNN_model = NearestNeighbors(n_neighbors=k, algorithm= "auto")
knn_model = KNN_model.fit(Wine_C)
distance, indices = knn_model.kneighbors(Prueba)

In [5]:
print ("K vecinos mas cercanos:")
for rank, index in enumerate(indices[0][:k], start = 1):
    print(str(rank) + " is", Wine_C.Alcohol[index])

K vecinos mas cercanos:
1 is 13.56
2 is 14.06
3 is 13.05
4 is 12.93
5 is 13.36

In [6]:
print("Promedios de alcohol aproximado:")
Alcohol_Vecinos = [Wine_C.Alcohol[i] for i in indices]
print("%.4f" %np.mean(Alcohol_Vecinos))

Promedios de alcohol aproximado:
13.3920

# Problema 2:
## Considere la lista de 11 compras desglosada de la manera siguiente:

In [7]:
my_basket = [['bread', 'butter', 'wine', 'bananas', 'coffee', 'carrots'],
             ['tomatoes', 'onions', 'cheese', 'milk', 'potatoes'],
             ['beer', 'chips', 'asparagus', 'salsa', 'milk', 'apples'],
             ['olive oil', 'bread', 'butter', 'tomatoes', 'steak', 'carrots'],
             ['tomatoes', 'onions', 'chips', 'wine', 'ketchup', 'orange juice'],
             ['bread', 'butter', 'beer', 'chips', 'milk'],
             ['butter', 'tomatoes', 'carrots', 'coffee', 'sugar'],
             ['tomatoes', 'onions', 'cheese', 'milk', 'potatoes'],
             ['bread', 'butter', 'ketchup', 'coffee', 'chicken wings'],
             ['butter', 'beer', 'chips', 'asparagus', 'apples'],
             ['tomatoes', 'onion', 'beer', 'chips', 'milk', 'coffee']]
my_basket

[['bread', 'butter', 'wine', 'bananas', 'coffee', 'carrots'],
 ['tomatoes', 'onions', 'cheese', 'milk', 'potatoes'],
 ['beer', 'chips', 'asparagus', 'salsa', 'milk', 'apples'],
 ['olive oil', 'bread', 'butter', 'tomatoes', 'steak', 'carrots'],
 ['tomatoes', 'onions', 'chips', 'wine', 'ketchup', 'orange juice'],
 ['bread', 'butter', 'beer', 'chips', 'milk'],
 ['butter', 'tomatoes', 'carrots', 'coffee', 'sugar'],
 ['tomatoes', 'onions', 'cheese', 'milk', 'potatoes'],
 ['bread', 'butter', 'ketchup', 'coffee', 'chicken wings'],
 ['butter', 'beer', 'chips', 'asparagus', 'apples'],
 ['tomatoes', 'onion', 'beer', 'chips', 'milk', 'coffee']]

## De acuerdo a la información anterior, se entiende que el primer ticket de compra de la lista consideró la adquisición de los siguientes productos: 
              bread   butter  wine  bananas  coffee  carrots

### Nota importante: tu programa debe ser capaz de correr cualquier lista de compras que venga en el mismo formato que el utilizado para esta actividad.

In [8]:
Productos_disponibles = [item for sublist in my_basket for item in sublist]
Prod_D = list(set(Productos_disponibles))

In [9]:
df = pd.DataFrame(columns=Prod_D) # Creacion del data frame con las columnas de contenido unico en la list previa

Col_Name = df.columns # Estraer columnas
N_Col = len(Col_Name) # Calcular cuantas columnas son
Row_Zeros = [0]*N_Col # Crear una fila con las columnas necesarias

for i in np.arange(len(my_basket)): # Acceder a la fila
    # print(i)
    df_temp = pd.DataFrame([Row_Zeros], columns=Col_Name) # Data frame temporal con fila llena de 0
    
    for j in np.arange(len(my_basket[i])): # Acceder a la columna
        df_temp.loc[:, df.columns.str.contains(my_basket[i][j])] = 1 # si La columna tiene el mismo nombre que el string,
                                                                # entonces esa columna es igual a 1

    df = pd.concat([df, df_temp]).reset_index(drop=True) # Concatenar Fila temporal (Dataframe temporal) con Dataframe
df

,tomatoes,milk,bread,ketchup,cheese,coffee,carrots,onion,apples,asparagus,...,orange juice,beer,potatoes,butter,sugar,salsa,chips,bananas,onions,wine
0,0,0,1,0,0,1,1,0,0,0,...,0,0,0,1,0,0,0,1,0,1
1,1,1,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
2,0,1,0,0,0,0,0,0,1,1,...,0,1,0,0,0,1,1,0,0,0
3,1,0,1,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,1,0,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,1,1
5,0,1,1,0,0,0,0,0,0,0,...,0,1,0,1,0,0,1,0,0,0
6,1,0,0,0,0,1,1,0,0,0,...,0,0,0,1,1,0,0,0,0,0
7,1,1,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
8,0,0,1,1,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,1,1,...,0,1,0,1,0,0,1,0,0,0
10,1,1,0,0,0,1,0,1,0,0,...,0,1,0,0,0,0,1,0,1,0

## Modifica el código explicado en este módulo para que sea capaz de realizar un análisis mediante el algoritmo “Market basket” a dicha lista de compras con la finalidad de detectar patrones de consumo. Realice a continuación las conclusiones que sean pertinentes sobre sus resultados.

In [10]:
# instalación del módulo mlxtend --- Por si no lo tenian instalado
!pip install mlxtend

Requirement already satisfied: mlxtend in c:\users\saulim\anaconda3\lib\site-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in c:\users\saulim\anaconda3\lib\site-packages (from mlxtend) (1.15.3)
Requirement already satisfied: numpy>=1.16.2 in c:\users\saulim\anaconda3\lib\site-packages (from mlxtend) (2.1.3)
Requirement already satisfied: pandas>=0.24.2 in c:\users\saulim\anaconda3\lib\site-packages (from mlxtend) (2.2.3)
Requirement already satisfied: scikit-learn>=1.3.1 in c:\users\saulim\anaconda3\lib\site-packages (from mlxtend) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\saulim\anaconda3\lib\site-packages (from mlxtend) (3.10.0)
Requirement already satisfied: joblib>=0.13.2 in c:\users\saulim\anaconda3\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\saulim\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\saulim\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\saulim\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\saulim\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\saulim\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\saulim\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\saulim\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\saulim\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\saulim\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\saulim\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\saulim\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\saulim\anaconda3\lib\site-packages (from scikit-learn>=1.3.1->mlxtend) (3.5.0)

In [11]:
# Aplicación del algoritmo "a priori" para localizar los articulos frecuentemente comprados en la base de datos
from mlxtend.frequent_patterns import apriori

# Analisis "a priori" con un soporte minimo del 3%
articulos_frec = apriori(df, min_support= 0.2, use_colnames= True)
articulos_frec = articulos_frec.sort_values("support", ascending= False)
articulos_frec = articulos_frec.reset_index(drop = True)

articulos_frec["length"] = articulos_frec["itemsets"].apply(lambda x: len(x))
articulos_frec

C:\Users\Saulim\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

     support                  itemsets  length
0   0.545455                (tomatoes)       1
1   0.545455                  (butter)       1
2   0.454545                   (chips)       1
3   0.454545                    (milk)       1
4   0.363636             (beer, chips)       2
5   0.363636           (bread, butter)       2
6   0.363636                  (onions)       1
7   0.363636        (tomatoes, onions)       2
8   0.363636                    (beer)       1
9   0.363636                  (coffee)       1
10  0.363636                   (bread)       1
11  0.272727          (tomatoes, milk)       2
12  0.272727                 (carrots)       1
13  0.272727              (beer, milk)       2
14  0.272727             (chips, milk)       2
15  0.272727            (onions, milk)       2
16  0.272727          (coffee, butter)       2
17  0.272727         (butter, carrots)       2
18  0.272727  (tomatoes, onions, milk)       3
19  0.272727       (beer, chips, milk)       3

In [12]:
from mlxtend.frequent_patterns import association_rules
association_rules(articulos_frec, metric = "confidence",
                 min_threshold = 0.7).sort_values("confidence", ascending = False).reset_index(drop = True)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(beer),(chips),0.363636,0.454545,0.363636,1.00,2.200000,1.0,0.198347,inf,0.857143,0.800000,1.000000,0.900000
1,(bread),(butter),0.363636,0.545455,0.363636,1.00,1.833333,1.0,0.165289,inf,0.714286,0.666667,1.000000,0.833333
2,(onions),(tomatoes),0.363636,0.545455,0.363636,1.00,1.833333,1.0,0.165289,inf,0.714286,0.666667,1.000000,0.833333
3,(carrots),(butter),0.272727,0.545455,0.272727,1.00,1.833333,1.0,0.123967,inf,0.625000,0.500000,1.000000,0.750000
4,"(beer, milk)",(chips),0.272727,0.454545,0.272727,1.00,2.200000,1.0,0.148760,inf,0.750000,0.600000,1.000000,0.800000
5,"(chips, milk)",(beer),0.272727,0.363636,0.272727,1.00,2.750000,1.0,0.173554,inf,0.875000,0.750000,1.000000,0.875000
6,"(onions, milk)",(tomatoes),0.272727,0.545455,0.272727,1.00,1.833333,1.0,0.123967,inf,0.625000,0.500000,1.000000,0.750000
7,"(tomatoes, milk)",(onions),0.272727,0.363636,0.272727,1.00,2.750000,1.0,0.173554,inf,0.875000,0.750000,1.000000,0.875000
8,(chips),(beer),0.454545,0.363636,0.363636,0.80,2.200000,1.0,0.198347,3.181818,1.000000,0.800000,0.685714,0.900000
9,(coffee),(butter),0.363636,0.545455,0.272727,0.75,1.375000,1.0,0.074380,1.818182,0.428571,0.428571,0.450000,0.625000
10,(beer),(milk),0.363636,0.454545,0.272727,0.75,1.650000,1.0,0.107438,2.181818,0.619048,0.500000,0.541667,0.675000
11,(onions),(milk),0.363636,0.454545,0.272727,0.75,1.650000,1.0,0.107438,2.181818,0.619048,0.500000,0.541667,0.675000
12,(onions),"(tomatoes, milk)",0.363636,0.272727,0.272727,0.75,2.750000,1.0,0.173554,2.909091,1.000000,0.750000,0.656250,0.875000
13,"(tomatoes, onions)",(milk),0.363636,0.454545,0.272727,0.75,1.650000,1.0,0.107438,2.181818,0.619048,0.500000,0.541667,0.675000
14,"(beer, chips)",(milk),0.363636,0.454545,0.272727,0.75,1.650000,1.0,0.107438,2.181818,0.619048,0.500000,0.541667,0.675000
15,(beer),"(chips, milk)",0.363636,0.272727,0.272727,0.75,2.750000,1.0,0.173554,2.909091,1.000000,0.750000,0.656250,0.875000

## Conclusiones

Debido a la poca cantidad de datos que tenemos se tuvo que establecer valores de support y de confianza bastante altos para que no imprimiera todas las combinaciones posibles, con eso dicho se puede ver que hay combinaciones con una confianza del 100% (para el ejemplo fueron 7) y que además hay varios con valores bastante elevados, al inicio se utilizó 50% pero aún eran demasiado conjuntos.

Este método KNN aunque no es tan visual debido a que utiliza muchas variables lo cual hace que no se pueda generar un gráfico 3D o 2D permite percatarnos acerca de grupos frecuentes entre productos.